DB schema implemented. Git ignore updated.
SWEN-746-Group-1/SIS-Plus-Plus pull request #23
Opened 2024-11-14 19:25 UTC by DCorcoran8543

Added DB models for all persistent components. Gitignore has been updated to ignore any script files added on local machines. We can undo this if we find the scripts to be universally helpful.

2024-11-14 22:06 UTC, DanRArcega reviewed
Good work! 
Schema seems to contain all the required information. I myself am less-versed in Prisma format, so I cannot comment on the syntax. I'll start implementing my section based on these values.

2024-11-14 23:20 UTC, rtyocum requested changes
For the most part looks fine. Few comments on missing relations and redundant fields.
The major thing I have is how catalogs are handled. Should they contain course sections or courses, and should they be tied to a semester. If there is only one catalog it feels dumb to keep it with one row in it

2024-11-14 23:20 UTC, rtyocum commented on prisma/schema.prisma
> +  sections CourseSection[] @ignore
Is there any reason to ignore these?

2024-11-14 23:20 UTC, rtyocum commented on prisma/schema.prisma
> +model Enrolled {
Thinking about renaming this to StudentEnrollment.
Seeing this for the first time I was thinking it was representitive of our old visitor pattern Enrollments

2024-11-14 23:20 UTC, rtyocum commented on prisma/schema.prisma
> +  studentId String
need relation to student. None exists meaning prisma can't fetch it

2024-11-14 23:20 UTC, rtyocum commented on prisma/schema.prisma
> +model Catalog {
How is this managed? Is there only one catalog that houses all the course sections or is it tied to a semester. Also should this be tied to courses and not sections? Otherwise grouping courses based on courses will be harder.

2024-11-14 23:21 UTC, rtyocum commented
Also changed the base to main, we want this merged sooner rather than later

2024-11-15 01:17 UTC, rtyocum approved these changes
Looks all good

2024-11-15 01:19 UTC, merged